### ISSUE TITLE
Add Label Documentation for Roadmap Project Management

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#3]
## Label Documentation

We want to share our thoughts and process for Project Management of the Legesher project and make the repositories of the project similar so it's easy to navigate between each one. 

- [x] Determine label set for the Legesher project
- [x] Assign colors for each of the labels 
- [x] Document the purpose of each of the labels 
- [x] Add the same labels and colors for the `legesher` repository
- [x] Add the same labels and colors for the `tree-sitter-legesher-python` repository
- [x] Add the same labels and colors for the `language-legesher-python` repository
- [x] Add the same labels and colors for the `legesher-docs` repository
- [x] Add the same labels and colors for the `legesher-dot-io` repository

**Comment by madiedgar** [comment]
Found a couple of repositories that do batch upload issues:
- [sshaw/batchlabels](https://github.com/sshaw/batchlabels)
- [Batch gemfiles](https://gist.github.com/chillu/45f9e9b777016f6257a64026aa84e0b3)

**Comment by madiedgar** [comment]
You can find the ruby gemfile in the `legesher-docs/legesher/labels` folder.
