### ISSUE TITLE
Add ZenHub Documentation for Roadmap Project Management

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#4]
## Label Documentation

We want to share our thoughts and process for Project Management of the Legesher project and make the repositories of the project similar so it's easy to navigate between each one. 

- [x] Determine sprint syntax for Github Milestones
- [x] Determine the sprint timeline for Github Milestones
- [x] Describe the purpose of each of the pipelines in the workspace
- [x] Describe story points and what each point might contain
- [x] Describe what is considered to be an Epic
- [x] Describe the current Epics and what is entailed within them
- [x] Describe Releases
