### ISSUE TITLE
Add Contributor's Guide for Roadmap Project Management

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#5]
## Label Documentation

We want to share our thoughts and process for Project Management of the Legesher project and make the repositories of the project similar so it's easy to navigate between each one. 

- [x] Describe Assignees to specific issues
- [x] Describe the process on how to contribute 
- [x] Describe how to gain access to the repositories
- [x] Note the location where contributors receive credit :tada:
